[package]
name = "rlib_io"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/maksim1744/rlib"
license = "MIT"
rust-version = "1.57.0"

[dependencies]
rlib_integer = { path = "../integer" }
