[package]
name = "rlib_geometry"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/maksim1744/rlib"
license = "MIT"
rust-version = "1.57.0"

[dependencies]
rlib_show = { path = "../show" }

[dev-dependencies]
rlib_rand = { path = "../rand" }
